# Generated by Django 5.2.2 on 2025-06-07 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CollageDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('canvas_width', models.PositiveIntegerField(help_text='Lebar canvas (px)')),
                ('canvas_height', models.PositiveIntegerField(help_text='Tinggi canvas (px)')),
                ('preview_image', models.ImageField(upload_to='collages/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='Identifier untuk PIL/opencv', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Urutan slot')),
                ('x', models.IntegerField(help_text='Posisi X (px)')),
                ('y', models.IntegerField(help_text='Posisi Y (px)')),
                ('width', models.PositiveIntegerField(help_text='Lebar slot (px)')),
                ('height', models.PositiveIntegerField(help_text='Tinggi slot (px)')),
                ('rotation', models.IntegerField(default=0, help_text='Rotation angle (°)')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='adminpanel.collagedesign')),
            ],
            options={
                'ordering': ['design', 'order'],
                'unique_together': {('design', 'order')},
            },
        ),
    ]
